Fix example makefiles to use proper path to symbol files
AcademySoftwareFoundation/openfx pull request #122
Opened 2023-06-15 17:05 UTC by garyo

The CMake builds are working now, but the examples were still using an old path to the symbol files.

2024-02-06 23:03 UTC, john-paulsmith requested changes
The changes now point to the correct path but the argument syntax is incorrect on macOS. Linux is fine.

2024-02-06 23:03 UTC, john-paulsmith commented on Examples/Makefile.master
> +    LINKFLAGS = $(BITSFLAG) -bundle -fvisibility=hidden -exported_symbols_list $(PATHTOROOT)../symbols/osx.symbols -framework OpenGL -Wl,-rpath,@loader_path/../Frameworks -Wl,-rpath,@loader_path/../L
I don't know if this syntax has changed, but it doesn't work correctly with the Xcode 15.2 toolchain. `-exported_symbols_list $(PATHTOROOT)../symbols/osx.symbols` should be `-Wl,exported_symbols_list,$(PATHTOROOT)../symbols/osx.symbols`.

2024-02-06 23:09 UTC, john-paulsmith commented
In my testing, I found that the symbol files are unnecessary on macOS and Linux - probably on Windows too but I'm not set up to test that easily. We set `-fvisibility=hidden` then in the code of our examples we include `__attribute__((visibility("default")))` on `OfxGetPlugin` and `OFXGetNumberOfPlugins`, which overrides the command-line arg and exports these symbols.

Not specifically related to this commit, but the CMake project has the same error in the macOS arguments. I will open a new PR to set visibility=hidden in a cross-platform way there.

2024-02-24 18:41 UTC, garyo commented
I have this working, but I see you've also got something similar in #141, @john-paulsmith . I'll merge your changes there into this or vice versa because this also has some only tangentially-related build fixes.

2024-02-24 21:44 UTC, merged